---
- hosts: VM1        
  remote_user: vagrant      

  become: yes
  tasks:                     # the task to be performed
  - name: uninstall python3 using apt-get
    ansible.builtin.apt: 
      name: 
        - python3-pip
        - python3-openstacksdk
        - python3-openstackclient
      state: absent 

  - name: unistall python libraries 
    ansible.builtin.pip:
      name: 
        - kafka-python
        - requests
        - python-openstackclient
        - openstacksdk 
        - git+https://github.com/chameleoncloud/python-blazarclient@chameleoncloud/stable/train
      state: absent
...