---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: couchdb   
  ports:
    - name: couchdb-port
      protocol: TCP    
      port: 5984  
      nodePort: 30006  ######### this is what will be externally published

...
