---

apiVersion: apps/v1
kind: Deployment         
metadata:
  name: kafka2-deployment 
  namespace: default
spec:                     
  replicas: 1             
  selector:
    matchLabels:
      app: kafka2        
  minReadySeconds: 5 
                         
  template:               
    metadata:
      labels:
        app: kafka2       
    spec: 
      hostname: kafka-broker2-host
      nodeSelector: 
        kubernetes.io/hostname: kubemaster   
      containers:
      - name: kafka2      # Used by DNS
        image: bitnami/kafka:latest                   
        ports:         
        - containerPort: 9092
        env:
          - name: KAFKA_CFG_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "PLAINTEXT://129.114.26.14:30002"
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "129.114.26.14:30000"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"