apiVersion: v1
kind: Service
metadata:
  name: kafka5-service
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: kafka5  
  ports:
    - name: kafka-broker5-port
      protocol: TCP    
      port: 9092 
      nodePort: 30005  #this is what will be externally published
