---
apiVersion: v1
kind: Service
metadata:
  name: kafka1-service
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: kafka1  
  ports:
    - name: kafka-broker1-port
      protocol: TCP    
      port: 9092 
      nodePort: 30001  # this is what will be externally published

...