apiVersion: v1
kind: Service
metadata:
  name: kafka2-service
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: kafka2  
  ports:
    - name: kafka-broker2-port
      protocol: TCP    
      port: 9092 
      nodePort: 30002  ######### this is what will be externally published

...