---

apiVersion: apps/v1
kind: Deployment        
metadata:
  name: kafka1-deployment
  namespace: default
spec:                    
  replicas: 1             
  selector:
    matchLabels:
      app: kafka1        
  minReadySeconds: 5 
                         
  template:              
    metadata:
      labels:
        app: kafka1       
    spec: 
      hostname: kafka-broker1-host
      nodeSelector: 
        kubernetes.io/hostname: kubemaster  
      containers:
      - name: kafka1      
        image: bitnami/kafka:latest                
        ports:         
        - containerPort: 9092
        env:
          - name: KAFKA_CFG_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "PLAINTEXT://129.114.26.14:30001"
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "129.114.26.14:30000" 
          - name:  KAFKA_BROKER_ID
            value: "0"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_TOPICS
            value: "OpenWeatherMap:1:5, Covid-19:1:5, AirQuality:1:5"
