---

apiVersion: apps/v1
kind: Deployment         
metadata:
  name: kafka5-deployment 
  namespace: default
spec:                     
  replicas: 1             
  selector:
    matchLabels:
      app: kafka5         
  minReadySeconds: 5  
                          
  template:               
    metadata:
      labels:
        app: kafka5        
    spec: 
      hostname: kafka-broker5-host
      nodeSelector: 
        kubernetes.io/hostname: kr-vm3   
      containers:
      - name: kafka5      # Used by DNS
        image: bitnami/kafka:latest                
        ports:         
        - containerPort: 9092
        env:
          - name: KAFKA_CFG_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "PLAINTEXT://129.114.25.56:30005"
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "129.114.26.14:30000"
          - name: KAFKA_BROKER_ID
            value: "4"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"