apiVersion: v1
kind: Service
metadata:
  name: kafka3-service
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: kafka3  
  ports:
    - name: kafka-broker3-port
      protocol: TCP    
      port: 9092 
      nodePort: 30003  ######### this is what will be externally published
