apiVersion: v1
kind: Service
metadata:
  name: kafka4-service
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: kafka4  
  ports:
    - name: kafka-broker4-port
      protocol: TCP    
      port: 9092 
      nodePort: 30004  ######### this is what will be externally published
