
apiVersion: batch/v1
kind: Job        
metadata:
  name: consumer-job  
  namespace: default 
spec:                   
  template:          
    metadata:
      labels:
        app: consumer       
    spec:   
      nodeSelector:  
        kubernetes.io/hostname: kubemaster          
      containers:
      - name: consumer      
        image: 10.56.0.127:5000/consumer-image:latest
        imagePullPolicy: Always  
        command: ["python3"]
        args: ["consumer.py"]  
      restartPolicy: Never 
