---

- hosts: MyChameleonVMs 
  remote_user:  cc    
  collections:   
    - openstack.cloud
 
  tasks:
  
  - name: Install python3 and java jdk using apt-get
    ansible.builtin.apt: 
      name: 
        - python3-pip
        - default-jdk
      update_cache: yes
    become: yes

  - name: download kafka
    ansible.builtin.unarchive:
      src: https://dlcdn.apache.org/kafka/3.2.0/kafka_2.13-3.2.0.tgz
      dest: /home/cc/
      remote_src: yes  
      mode: '0700'

  - name: move kafka downloaded folder to kafka folder
    ansible.builtin.shell: mv /home/cc/kafka_2.13-3.2.0 /home/cc/kafka   

  - name: pip upgrade
    ansible.builtin.pip:
      name: pip
      extra_args: --upgrade
      executable: pip3

- hosts: VM2 # VM2
  remote_user:  cc   
  collections:  
    - openstack.cloud
  become: yes

  tasks:
  - name: Install python couchdb 
    ansible.builtin.pip: 
      name: 
        - couchdb  
        - kafka-python




...