---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: default
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: zookeeper  
  ports:
    - name: zookeeper-port
      protocol: TCP    
      port: 2181  
      targetPort: 2181
      nodePort: 30000  ######### this is what will be externally published
...
