---

apiVersion: apps/v1
kind: Deployment        
metadata:
  name: zookeeper-deployment  
  namespace: default
spec:                     
  replicas: 1            
  selector:
    matchLabels:
      app: zookeeper         
  minReadySeconds: 5  
                          
  template:               
    metadata:
      labels:
        app: zookeeper       
    spec: 
      hostname: zookeeper-host
      nodeSelector: 
        kubernetes.io/hostname: kubemaster  
      containers:
      - name: zookeeper       # Used by DNS
        image: bitnami/zookeeper:latest          
        ports:         
        - containerPort: 2181
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
  