---
- hosts: VM1 
  remote_user: vagrant
  become: yes     # run with "sudo" privileges 
  gather_facts: no
  pre_tasks:                     # the task to be performed
  - name: Install python3 packages using apt-get
    ansible.builtin.apt: 
      name: 
        - python3-pip
        - python3-openstackclient
        - python3-openstacksdk
      state: latest
      state: present
        
  tasks:
  - name: install ansible galaxy os
    ansible.builtin.shell: ansible-galaxy collection install openstack.cloud

  - name: pip upgrade
    ansible.builtin.pip:
      name: pip
      extra_args: --upgrade
      executable: pip3
  - name: Install pythons libraries 
    ansible.builtin.pip:
      name:
        - kafka-python
        - requests 
        - python-openstackclient
        - openstacksdk==0.61.0  
        - git+https://github.com/chameleoncloud/python-blazarclient@chameleoncloud/stable/train

...