---

- hosts: VM2
  remote_user:  cc    
  collections:   
    - openstack.cloud
 
  tasks:

  - name: Create a Service for zookeeper
    kubernetes.core.k8s:
      state: present
      src: ~/zookeeper/zookeeper-service.yaml
  
  - name: Create a Deployment for zookeeper 
    kubernetes.core.k8s:
      state: present
      src: ~/zookeeper/zookeeper-deployment.yaml

  - name: wait a for container creation 
    ansible.builtin.wait_for:
      timeout: 5

  ############ kafka deployments/services ############

  - name: Create a Service for kafka1
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka1-service.yaml
      
  - name: Create a Deployment for kafka1 
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka1-deployment.yaml


  - name: Create a Service for kafka2
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka2-service.yaml
      
  - name: Create a Deployment for kafka2 
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka2-deployment.yaml



  - name: Create a Service for kafka3
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka3-service.yaml  

  - name: Create a Deployment for kafka3 
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka3-deployment.yaml

  

  - name: Create a Service for kafka4
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka4-service.yaml

  - name: Create a Deployment for kafka4  
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka4-deployment.yaml



  - name: Create a Service for kafka5
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka5-service.yaml

  - name: Create a Deployment for kafka5 
    kubernetes.core.k8s:
      state: present
      src: ~/kafka/kafka5-deployment.yaml

...